In [1]:
from utility.plot_spectrum import plot_spectrum
from utility.adjust_redshift import adjust_redshift

from sparcl.client import SparclClient
from dl import queryClient as qc

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

plt.rcParams.update({"legend.frameon":False})

### prepare Hamann ERQ data

#### clean core ERQ dataframe

In [29]:
hamann_erq = pd.read_csv("data/Hamann2017-core-ERQ-stats.csv", skiprows=[1])


## rename columns
col_rename_dic = {
            "Quasar name":"SDSS_id",
            "N V/C IV":"NV/CIV",
            "αλ":"UV_slope",
            "E(B − V)":"E(B-V)",
            "i–W3":"i-W3"
            }

hamann_erq = hamann_erq.rename(columns=col_rename_dic)


## change weird - into nan
hamann_erq = hamann_erq.replace("–",np.nan)  


## split up uncertainties to new columns, turn into floats
hamann_erq["REW_unc"] = hamann_erq["REW"].apply(lambda x: x.split("±")[1]).astype("float")
hamann_erq["REW"] = hamann_erq["REW"].apply(lambda x: x.split("±")[0]).astype("float")

hamann_erq["FWHM_unc"] = hamann_erq["FWHM"].apply(lambda x: x.split("±")[1]).astype("float")
hamann_erq["FWHM"] = hamann_erq["FWHM"].apply(lambda x: x.split("±")[0]).astype("float")

hamann_erq["E(B-V)_unc"] = hamann_erq["E(B-V)"].astype(str).apply(lambda x: x.split("±"))  # has nan values hence the extra step inbetween
hamann_erq["E(B-V)"] = hamann_erq["E(B-V)_unc"].apply(lambda x: x[0]).astype("float")
hamann_erq["E(B-V)_unc"] = hamann_erq["E(B-V)_unc"].apply(lambda x: x[1] if len(x) > 1 else x[0]).astype("float")

hamann_erq["FIRST"] = hamann_erq["FIRST"].astype("float")


## turn that stubborn dumbass UV_slope column into floats, no idea why the sane way does not work
def convert_weird_minus_to_float(value):
    if value[0] == "−":
        value = value[1:]
        return float(value)*(-1)
    else:
        return float(value)

hamann_erq["UV_slope"] = hamann_erq["UV_slope"].apply(lambda x: convert_weird_minus_to_float(x))


## change column order
hamann_erq = hamann_erq[['SDSS_id', 'ze', 'i', 'i-W3', 'REW', 'REW_unc', 'FWHM', 'FWHM_unc', 'kt80', 'NV/CIV', 'BAL', 'UV_slope', 'E(B-V)', 'E(B-V)_unc', 'FIRST']]

hamann_erq

,SDSS_id,ze,i,i-W3,REW,REW_unc,FWHM,FWHM_unc,kt80,NV/CIV,BAL,UV_slope,E(B-V),E(B-V)_unc,FIRST
0,J000610.67+121501.2a,2.31,22.1,8.0,107.0,6.0,4540.0,200.0,0.37,1.88,0,-0.20,0.66,0.01,0.0
1,J000746.19+122223.9,2.43,21.3,4.9,220.0,6.0,2433.0,71.0,0.28,0.39,0,-0.17,0.19,0.01,0.0
2,J002400.25+245031.9,2.81,21.6,6.0,144.0,10.0,3523.0,195.0,0.37,2.46,0,-1.14,0.20,0.02,NaN
3,J004713.21+264024.7,2.56,20.4,4.7,101.0,2.0,3685.0,74.0,0.33,1.92,1,-1.08,0.15,0.01,NaN
4,J005044.95−021217.6,2.25,21.5,4.7,147.0,9.0,4343.0,487.0,0.19,0.61,0,-1.73,0.14,0.02,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,J223754.52+065026.6,2.61,22.0,5.8,141.0,5.0,1391.0,44.0,0.36,1.03,0,-1.20,0.24,0.02,0.0
93,J225438.30+232714.5,3.09,22.0,5.5,415.0,20.0,4412.0,146.0,0.36,0.66,0,-0.38,NaN,NaN,NaN
94,J232326.17−010033.1a,2.36,22.4,7.2,256.0,5.0,3989.0,62.0,0.37,2.16,0,0.91,0.40,0.01,0.0
95,J232828.47+044346.8,2.56,21.5,5.5,359.0,5.0,1584.0,20.0,0.35,0.37,0,-0.28,0.13,0.02,0.0
96,J233636.99+065231.0,2.78,22.2,6.0,128.0,6.0,1484.0,83.0,0.26,1.10,0,-0.19,NaN,NaN,0.0

In [28]:
hamann_erq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SDSS_id     97 non-null     object
 1   ze          97 non-null     float64
 2   i           97 non-null     float64
 3   i-W3        97 non-null     float64
 4   REW         97 non-null     float64
 5   REW_unc     97 non-null     float64
 6   FWHM        97 non-null     float64
 7   FWHM_unc    97 non-null     float64
 8   kt80        97 non-null     float64
 9   NV/CIV      97 non-null     float64
 10  BAL         97 non-null     int64
 11  UV_slope    97 non-null     float64
 12  E(B-V)      87 non-null     float64
 13  E(B-V)_unc  87 non-null     float64
 14  FIRST       91 non-null     float64
dtypes: float64(13), int64(1), object(1)
memory usage: 11.5+ KB

#### extract positions of ERQs from SDSS

### Find Hamann ERQ in DESI

In [ ]:
query = """
        SELECT targetid, target_ra, target_dec, z, 
        FROM desi_dr1.agnqso
        LIMIT 1000
        """

results = qc.query(sql=query, fmt="pandas")

In [16]:
results.head(50)

             targetid             ls_id
0   39633180159908726  9907736513026934
1   39633180159908110  9907736513026318
2   39633175927855592  9907736446900712
3   39633180159906587  9907736513024795
4   39633180159908251  9907736513026459
5   39633180164097697  9907736513087137
6   39633180164098202  9907736513087642
7   39633180159908219  9907736513026427
8   39633180164096180  9907736513085620
9   39633180164096335  9907736513085775
10  39633180164096472  9907736513085912
11  39633180159908043  9907736513026251
12  39633180159905004  9907736513023212
13  39633180159905484  9907736513023692
14  39633180155714167  9907736512961143
15  39633180159902940  9907736513021148
16  39633180159906719  9907736513024927
17  39633180159905489  9907736513023697
18  39633180159906760  9907736513024968
19  39633180159903855  9907736513022063
20  39633180159902909  9907736513021117
21  39633180159903315  9907736513021523
22  39633180159903512  9907736513021720
23  39633180168295644  9907736513156316
24  39633180168294453  9907736513155125
25  39633180168295772  9907736513156444
26  39633180168294287  9907736513154959
27  39633180168292210  9907736513152882
28  39633180168292385  9907736513153057
29  39633184383569883  9907736579018715
30  39633184383569265  9907736579018097
31  39633184383567906  9907736579016738
32  39633180164103079  9907736513092519
33  39633180164102579  9907736513092019
34  39633180168290674  9907736513151346
35  39633180164102178  9907736513091618
36  39633180164100759  9907736513090199
37  39633180164100182  9907736513089622
38  39633180164101345  9907736513090785
39  39633184379376220  9907736578953820
40  39633180164100165  9907736513089605
41  39633180164099857  9907736513089297
42  39633184379378504  9907736578956104
43  39633184383566613  9907736579015445
44  39633184379377004  9907736578954604
45  39633184379377761  9907736578955361
46  39633184379378451  9907736578956051
47  39633184379375364  9907736578952964
48  39633184379377065  9907736578954665
49  39633184379376088  9907736578953688

In [11]:
print(qc.schema('desi_dr1.zpix'))

Schema: desi_dr1
 Table: zpix

     Column Name   Description
     -----------   -----------
            elon   Ecliptic longitude
            elat   Ecliptic latitude
            glon   Galactic longitude
            glat   Galactic latitude
               z   Redshift measured by Redrock
            zerr   Redshift error from Redrock
            chi2   Best fit chi squared
         coeff_0   Redrock template coefficients
         coeff_1   Redrock template coefficients
         coeff_2   Redrock template coefficients
         coeff_3   Redrock template coefficients
         coeff_4   Redrock template coefficients
         coeff_5   Redrock template coefficients
         coeff_6   Redrock template coefficients
         coeff_7   Redrock template coefficients
         coeff_8   Redrock template coefficients
         coeff_9   Redrock template coefficients
       deltachi2   Delta-chi-squared for template fit from Redrock
   mean_fiber_ra   Mean (over exposures) RA of actual fiber position
  mean_fiber_dec   Mean (over exposures) DEC of actual fiber position
              id   Arbitrary primary key composed from targetid, survey, prog
                   ram. NOTE: this column is stored as a NUMERIC(39,0) dataty
                   pe.
        targetid   Unique DESI target ID
   coadd_exptime   Sum of the exposure times contributing to the coadd for th
                   is target
    mean_delta_x   Mean (over exposures) fiber difference between measured an
                   d requested CS5 X location on focal plane
     rms_delta_x   RMS (over exposures) of the fiber difference between measu
                   red and requested CS5 X location on focal plane
    mean_delta_y   Mean (over exposures) fiber difference between measured an
                   d requested CS5 Y location on focal plane
     rms_delta_y   RMS (over exposures) of the fiber difference between measu
                   red and requested CS5 Y location on focal plane
    std_fiber_ra   Standard deviation (over exposures) of RA of actual fiber
                   position
   std_fiber_dec   Standard deviation (over exposures) of DEC of actual fiber
                   position
mean_psf_to_fiber_specflux   Mean of the PSF_TO_FIBER_SPECFLUX values of the spectra us
                   ed in the coadd
 tsnr2_gpbdark_b   GPBDARK B template (S/N)^2
     tsnr2_elg_b   ELG B template (S/N)^2
tsnr2_gpbbright_b   GPBBRIGHT B template (S/N)^2
     tsnr2_lya_b   LYA B template (S/N)^2
     tsnr2_bgs_b   BGS B template (S/N)^2
tsnr2_gpbbackup_b   GPBBACKUP B template (S/N)^2
     tsnr2_qso_b   QSO B template (S/N)^2
     tsnr2_lrg_b   LRG B template (S/N)^2
 tsnr2_gpbdark_r   GPBDARK R template (S/N)^2
     tsnr2_elg_r   ELG R template (S/N)^2
tsnr2_gpbbright_r   GPBBRIGHT R template (S/N)^2
     tsnr2_lya_r   LYA R template (S/N)^2
     tsnr2_bgs_r   BGS R template (S/N)^2
tsnr2_gpbbackup_r   GPBBACKUP R template (S/N)^2
     tsnr2_qso_r   QSO R template (S/N)^2
     tsnr2_lrg_r   LRG R template (S/N)^2
 tsnr2_gpbdark_z   GPBDARK Z template (S/N)^2
     tsnr2_elg_z   ELG Z template (S/N)^2
tsnr2_gpbbright_z   GPBBRIGHT Z template (S/N)^2
     tsnr2_lya_z   LYA Z template (S/N)^2
     tsnr2_bgs_z   BGS Z template (S/N)^2
tsnr2_gpbbackup_z   GPBBACKUP Z template (S/N)^2
     tsnr2_qso_z   QSO Z template (S/N)^2
     tsnr2_lrg_z   LRG Z template (S/N)^2
   tsnr2_gpbdark   GPBDARK template (S/N)^2 summed over B, R, Z
       tsnr2_elg   ELG template (S/N)^2 summed over B, R, Z
 tsnr2_gpbbright   GPBBRIGHT template (S/N)^2 summed over B, R, Z
       tsnr2_lya   LYA template (S/N)^2 summed over B, R, Z
       tsnr2_bgs   BGS template (S/N)^2 summed over B, R, Z
 tsnr2_gpbbackup   GPBBACKUP template (S/N)^2 summed over B, R, Z
       tsnr2_qso   QSO template (S/N)^2 summed over B, R, Z
       tsnr2_lrg   LRG template (S/N)^2 summed over B, R, Z
       random_id   Random ID in the range 0.0 => 100.0 (not unique)
        spgrpval   Value corresponding to the grouping type indicated in the
                   spgrp column. For zpix table this is the same as the healp
                   ix column
         healpix   HEALPixel containing this location at NSIDE=64 in the NEST
                   ED scheme
coadd_fiberstatus   Bitwise AND of the FIBERSTATUS values of the spectra used
                   in the coadd
            htm9   Ninth level (~10 arcmin resolution) Hierarchical Triangula
                   r Mesh index (Szalay et al. 2007)
         ring256   Ring-scheme HEALPix (Gorski et al. 2005) index with Nsides
                   =256 (~14 arcmin size)
        nest4096   Nested-scheme HEALPix (Gorski et al. 2005) index with Nsid
                   es=4096 (~52 arcsec size)
           zwarn   Redshift warning bitmask measured by Redrock
         npixels   Number of unmasked wavelengths that contributed to the red
                   shift fit
          ncoeff   Number of Redrock template coefficients
    coadd_numexp   Number of exposures included in the coadd for this target
  coadd_numnight   Number of different nights included in the coadd for this
                   target
   coadd_numtile   Number of different tiles included in the coadd for this target
        sv_nspec   Number of coadded spectra for this TARGETID in SV (SV1+2+3)
      main_nspec   Number of coadded spectra for this TARGETID in Main survey
      zcat_nspec   Number of coadded spectra for this TARGETID in this zcatalog
      sv_primary   True/False flag for the primary coadded spectrum in SV (SV
                   1+2+3)
    main_primary   True/False flag for the primary coadded spectrum in Main survey
    zcat_primary   True/False flag for the primary coadded spectrum in this z
                   catalog
           spgrp   Type of spectral grouping. For zpix table this is always =
                   healpix
         subtype   Spectral subtype
         program   DESI program type - BRIGHT, DARK, or BACKUP
        spectype   Spectype from Redrock file
          survey   Survey name
        mean_mjd   Mean value of the Modified Julian Date (when the shutter w
                   as open for exposures used in the coadded spectrum)
         min_mjd   Minimum value of the Modified Julian Date (when the shutte
                   r was open for the first exposure used in the coadded spec
                   trum)
         max_mjd   Maximum value of the Modified Julian Date (when the shutte
                   r was open for the last exposure used in the coadded spect
                   rum)
      mws_target   Milky Way Survey targeting bits
  sv1_mws_target   MWS (bright time program) target selection bitmask for SV1
  sv2_mws_target   MWS (bright time program) target selection bitmask for SV2
  sv3_mws_target   MWS (bright time program) target selection bitmask for SV3
     scnd_target   Target selection bitmask for secondary programs
 sv1_scnd_target   Secondary target selection bitmask for SV1
 sv2_scnd_target   Secondary target selection bitmask for SV2
 sv3_scnd_target   Secondary target selection bitmask for SV3
      bgs_target   BGS (bright time program) target selection bitmask
  sv1_bgs_target   BGS (bright time program) target selection bitmask for SV1
  sv2_bgs_target   BGS (bright time program) target selection bitmask for SV2
  sv3_bgs_target   BGS (bright time program) target selection bitmask for SV3
     desi_target   Dark survey + calibration targeting bits
 sv1_desi_target   DESI (dark time program) target selection bitmask for SV1
 sv2_desi_target   DESI (dark time program) target selection bitmask for SV2
 sv3_desi_target   DESI (dark time program) target selection bitmask for SV3
      cmx_target   Target selection bitmask for commissioning
        desiname   Human-readable identifier of a sky location DESI JXXX.XXXX
                   [+/-]YY.YYYY, where X,Y=truncated decimal target_ra, targe
                   t_dec, precise to 0.36 arcsec